"use client";

import { motion, useInView, AnimatePresence } from "framer-motion";
import { useRef, useState, useEffect, useCallback } from "react";

interface Testimonial {
  name: string;
  profession: string;
  rating: number;
  message: string;
  initials: string;
  color: string;
}

const sampleTestimonials: Testimonial[] = [
  {
    name: "Rajesh Kumar",
    profession: "E-Commerce Director",
    rating: 4.5,
    message:
      "JARVIS transformed how we analyze our business data. The AI-driven insights helped us identify inventory issues we never would have caught manually.",
    initials: "RK",
    color: "from-[#FF7200] to-cyan-500",
  },
  {
    name: "Priya Sharma",
    profession: "Retail Operations Manager",
    rating: 5,
    message:
      "The behavioral monitoring system is incredible. We detected fraudulent patterns early and saved significant revenue. Truly intelligent commerce.",
    initials: "PS",
    color: "from-[#FF7200] to-purple-500",
  },
  {
    name: "Arjun Mehta",
    profession: "Tech Startup Founder",
    rating: 4,
    message:
      "The strategic reports generated by JARVIS are remarkably detailed. It feels like having a full analytics team powered by AI working around the clock.",
    initials: "AM",
    color: "from-emerald-500 to-teal-500",
  },
  {
    name: "Sneha Reddy",
    profession: "Supply Chain Analyst",
    rating: 4.5,
    message:
      "Inventory intelligence features are game-changing. Restocking recommendations are accurate and have reduced our overhead significantly.",
    initials: "SR",
    color: "from-pink-500 to-rose-500",
  },
  {
    name: "Vikram Patel",
    profession: "Business Intelligence Lead",
    rating: 5,
    message:
      "From raw data to actionable insights in seconds. JARVIS bridges the gap between descriptive analytics and prescriptive decision-making beautifully.",
    initials: "VP",
    color: "from-amber-500 to-orange-500",
  },
  {
    name: "Deepa Nair",
    profession: "Product Manager",
    rating: 3.5,
    message:
      "Solid platform with great AI capabilities. The Silicon Consultant feature provides strategic reports that align well with our business objectives.",
    initials: "DN",
    color: "from-[#FF7200] to-[#FF7200]",
  },
];

function StarRating({ rating }: { rating: number }) {
  return (
    <div className="flex items-center gap-0.5">
      {[1, 2, 3, 4, 5].map((star) => {
        const fill = Math.min(Math.max(rating - star + 1, 0), 1);
        return (
          <div key={star} className="relative w-4 h-4">
            {/* Empty star */}
            <svg
              viewBox="0 0 24 24"
              className="absolute inset-0 w-4 h-4"
              fill="none"
              stroke="rgba(255,255,255,0.15)"
              strokeWidth="1.5"
            >
              <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
            </svg>
            {/* Filled star with clip */}
            <div
              className="absolute inset-0 overflow-hidden"
              style={{ width: `${fill * 100}%` }}
            >
              <svg
                viewBox="0 0 24 24"
                className="w-4 h-4"
                fill="#F59E0B"
                stroke="none"
              >
                <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
              </svg>
            </div>
          </div>
        );
      })}
    </div>
  );
}

function TestimonialCard({ testimonial }: { testimonial: Testimonial }) {
  return (
    <div
      className="flex-shrink-0 w-[340px] md:w-[380px]"
    >
      <div className="glass-card p-6 h-full bg-white/[0.03] backdrop-blur-xl border border-white/[0.06]">
        {/* Profile */}
        <div className="flex items-center gap-3 mb-4">
          <div
            className={`w-11 h-11 rounded-full bg-gradient-to-br ${testimonial.color} flex items-center justify-center flex-shrink-0`}
          >
            <span className="text-sm font-bold text-white">
              {testimonial.initials}
            </span>
          </div>
          <div>
            <h4 className="text-sm font-semibold text-white/85">
              {testimonial.name}
            </h4>
            <p className="text-[11px] text-white/35">{testimonial.profession}</p>
          </div>
        </div>

        {/* Stars */}
        <div className="mb-3">
          <StarRating rating={testimonial.rating} />
        </div>

        {/* Message */}
        <p className="text-sm text-white/45 leading-relaxed">
          &ldquo;{testimonial.message}&rdquo;
        </p>
      </div>
    </div>
  );
}

function RatingForm({ onSubmit, onClose }: { onSubmit: (t: Testimonial) => void; onClose: () => void }) {
  const [name, setName] = useState("");
  const [profession, setProfession] = useState("");
  const [rating, setRating] = useState(0);
  const [hoverRating, setHoverRating] = useState(0);
  const [message, setMessage] = useState("");
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = () => {
    if (!name.trim() || !profession.trim() || rating === 0 || !message.trim()) return;
    const initials = name
      .split(" ")
      .map((n) => n[0])
      .join("")
      .toUpperCase()
      .slice(0, 2);
    const colors = [
      "from-[#FF7200] to-cyan-500",
      "from-[#FF7200] to-purple-500",
      "from-emerald-500 to-teal-500",
      "from-pink-500 to-rose-500",
      "from-amber-500 to-orange-500",
      "from-[#FF7200] to-[#FF7200]",
    ];
    onSubmit({
      name,
      profession,
      rating,
      message,
      initials,
      color: colors[Math.floor(Math.random() * colors.length)],
    });
    setSubmitted(true);
  };

  if (submitted) {
    return (
      <div className="glass-card p-8 text-center">
        <div className="w-14 h-14 rounded-full bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center mx-auto mb-4">
          <span className="text-xl">✓</span>
        </div>
        <h4 className="text-lg font-bold text-white mb-2">Thank You!</h4>
        <p className="text-sm text-white/40 mb-4">Your testimonial has been submitted.</p>
        <button
          onClick={onClose}
          className="px-5 py-2 text-sm text-[#FF9040] border border-[#FF7200]/20 rounded-xl hover:bg-[#FF7200]/10 transition-colors"
        >
          Close
        </button>
      </div>
    );
  }

  return (
    <div className="glass-card p-6 space-y-4">
      <div className="flex items-center justify-between mb-2">
        <h4 className="text-lg font-bold text-white/90">Share Your Experience</h4>
        <button onClick={onClose} className="text-white/30 hover:text-white/60 text-lg transition-colors">
          ✕
        </button>
      </div>

      <div>
        <label className="block font-mono text-[10px] text-white/30 tracking-widest uppercase mb-1.5">
          Your Name *
        </label>
        <input
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
          className="w-full px-4 py-2.5 bg-white/[0.03] border border-white/8 rounded-lg text-sm text-white/80 placeholder:text-white/15 focus:outline-none focus:border-[#FF7200]/50 transition-colors"
          placeholder="Enter your full name"
        />
      </div>

      <div>
        <label className="block font-mono text-[10px] text-white/30 tracking-widest uppercase mb-1.5">
          Your Profession *
        </label>
        <input
          type="text"
          value={profession}
          onChange={(e) => setProfession(e.target.value)}
          className="w-full px-4 py-2.5 bg-white/[0.03] border border-white/8 rounded-lg text-sm text-white/80 placeholder:text-white/15 focus:outline-none focus:border-[#FF7200]/50 transition-colors"
          placeholder="e.g. Business Analyst"
        />
      </div>

      <div>
        <label className="block font-mono text-[10px] text-white/30 tracking-widest uppercase mb-1.5">
          Rating *
        </label>
        <div className="flex items-center gap-1">
          {[1, 2, 3, 4, 5].map((star) => {
            const activeRating = hoverRating || rating;
            const fill = Math.min(Math.max(activeRating - star + 1, 0), 1);
            return (
              <button
                key={star}
                type="button"
                className="relative w-7 h-7 cursor-pointer group"
                onMouseEnter={() => setHoverRating(star - 0.5)}
                onMouseLeave={() => setHoverRating(0)}
                onClick={() => setRating(star)}
              >
                {/* Left half */}
                <div
                  className="absolute left-0 top-0 w-1/2 h-full z-10"
                  onMouseEnter={() => setHoverRating(star - 0.5)}
                  onClick={() => setRating(star - 0.5)}
                />
                {/* Right half */}
                <div
                  className="absolute right-0 top-0 w-1/2 h-full z-10"
                  onMouseEnter={() => setHoverRating(star)}
                  onClick={() => setRating(star)}
                />
                {/* Empty star */}
                <svg
                  viewBox="0 0 24 24"
                  className="absolute inset-0 w-7 h-7"
                  fill="none"
                  stroke="rgba(255,255,255,0.15)"
                  strokeWidth="1.5"
                >
                  <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
                </svg>
                {/* Filled */}
                <div
                  className="absolute inset-0 overflow-hidden"
                  style={{ width: `${fill * 100}%` }}
                >
                  <svg viewBox="0 0 24 24" className="w-7 h-7" fill="#F59E0B" stroke="none">
                    <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
                  </svg>
                </div>
              </button>
            );
          })}
          {rating > 0 && (
            <span className="ml-2 text-sm text-amber-400 font-mono">{rating}</span>
          )}
        </div>
      </div>

      <div>
        <label className="block font-mono text-[10px] text-white/30 tracking-widest uppercase mb-1.5">
          Your Feedback *
        </label>
        <textarea
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          rows={3}
          className="w-full px-4 py-2.5 bg-white/[0.03] border border-white/8 rounded-lg text-sm text-white/80 placeholder:text-white/15 focus:outline-none focus:border-[#FF7200]/50 transition-colors resize-none"
          placeholder="Share your experience with us..."
        />
      </div>

      <button
        onClick={handleSubmit}
        disabled={!name.trim() || !profession.trim() || rating === 0 || !message.trim()}
        className="w-full py-2.5 px-6 bg-[#E66800] hover:bg-[#FF7200] disabled:bg-[#E66800]/30 disabled:text-white/30 text-white font-medium rounded-xl transition-all text-sm"
      >
        Submit Testimonial
      </button>
    </div>
  );
}

export default function Testimonials() {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, margin: "-100px" });
  const scrollRef = useRef<HTMLDivElement>(null);
  const [testimonials, setTestimonials] = useState<Testimonial[]>(sampleTestimonials);
  const [isHovered, setIsHovered] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const scrollIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const autoScroll = useCallback(() => {
    if (!scrollRef.current) return;
    const el = scrollRef.current;
    if (el.scrollLeft >= el.scrollWidth - el.clientWidth - 1) {
      el.scrollTo({ left: 0, behavior: "smooth" });
    } else {
      el.scrollBy({ left: 1, behavior: "auto" });
    }
  }, []);

  useEffect(() => {
    if (inView && !isHovered) {
      scrollIntervalRef.current = setInterval(autoScroll, 30);
    }
    return () => {
      if (scrollIntervalRef.current) clearInterval(scrollIntervalRef.current);
    };
  }, [inView, isHovered, autoScroll]);

  const scrollByAmount = (dir: number) => {
    if (scrollRef.current) {
      scrollRef.current.scrollBy({ left: dir * 400, behavior: "smooth" });
    }
  };

  return (
    <section className="relative py-24 md:py-32 overflow-hidden" ref={ref}>
      <div className="absolute inset-0 bg-gradient-to-b from-[#080808] via-[#0B0B0D] to-[#080808]" />
      <div className="absolute inset-0 tech-grid opacity-5" />
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[400px] bg-amber-600/3 rounded-full blur-[150px]" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Header */}
        <motion.div
          className="mb-12"
          initial={{ opacity: 0, y: 30 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.7 }}
        >
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-white/10 bg-white/5 mb-6">
            <span className="font-mono text-[10px] text-amber-400/70 tracking-widest uppercase">
              Testimonials
            </span>
          </div>
          <div className="flex items-end justify-between flex-wrap gap-4">
            <div>
              <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold">
                What People
                <br />
                <span className="bg-gradient-to-r from-amber-400 to-orange-400 bg-clip-text text-transparent">
                  Are Saying
                </span>
              </h2>
            </div>
            <button
              onClick={() => setShowForm(!showForm)}
              className="px-5 py-2.5 text-sm font-medium text-amber-400 border border-amber-500/20 rounded-xl hover:bg-amber-500/10 transition-colors flex items-center gap-2"
            >
              {showForm ? "Close" : "Give Rating"} {!showForm && <span>→</span>}
            </button>
          </div>
        </motion.div>

        {/* Rating Form */}
        <AnimatePresence>
          {showForm && (
            <motion.div
              className="mb-8 max-w-lg"
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              exit={{ opacity: 0, height: 0 }}
              transition={{ duration: 0.3 }}
            >
              <RatingForm
                onSubmit={(t) => setTestimonials((prev) => [t, ...prev])}
                onClose={() => setShowForm(false)}
              />
            </motion.div>
          )}
        </AnimatePresence>

        {/* Testimonial carousel */}
        <div
          className="relative group"
          onMouseEnter={() => setIsHovered(true)}
          onMouseLeave={() => setIsHovered(false)}
        >
          {/* Scroll container */}
          <div
            ref={scrollRef}
            className="flex gap-5 overflow-x-auto pb-4 scrollbar-hide"
            style={{
              scrollbarWidth: "none",
              msOverflowStyle: "none",
              WebkitOverflowScrolling: "touch",
            }}
          >
            {testimonials.map((t, i) => (
              <motion.div
                key={`${t.name}-${i}`}
                initial={{ opacity: 0, y: 20 }}
                animate={inView ? { opacity: 1, y: 0 } : {}}
                transition={{ duration: 0.5, delay: i * 0.1 }}
              >
                <TestimonialCard testimonial={t} />
              </motion.div>
            ))}
          </div>

          {/* Navigation arrows - visible on hover */}
          <AnimatePresence>
            {isHovered && (
              <>
                <motion.button
                  initial={{ opacity: 0, x: 10 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: 10 }}
                  onClick={() => scrollByAmount(-1)}
                  className="absolute left-0 top-1/2 -translate-y-1/2 -translate-x-4 w-10 h-10 rounded-full bg-white/[0.08] backdrop-blur-xl border border-white/10 flex items-center justify-center text-white/60 hover:text-white hover:bg-white/[0.12] transition-all z-20"
                >
                  <svg viewBox="0 0 24 24" className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M15 18l-6-6 6-6" />
                  </svg>
                </motion.button>
                <motion.button
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -10 }}
                  onClick={() => scrollByAmount(1)}
                  className="absolute right-0 top-1/2 -translate-y-1/2 translate-x-4 w-10 h-10 rounded-full bg-white/[0.08] backdrop-blur-xl border border-white/10 flex items-center justify-center text-white/60 hover:text-white hover:bg-white/[0.12] transition-all z-20"
                >
                  <svg viewBox="0 0 24 24" className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M9 18l6-6-6-6" />
                  </svg>
                </motion.button>
              </>
            )}
          </AnimatePresence>

          {/* Fade edges */}
          <div className="absolute left-0 top-0 bottom-4 w-16 bg-gradient-to-r from-[#080808] to-transparent pointer-events-none z-10" />
          <div className="absolute right-0 top-0 bottom-4 w-16 bg-gradient-to-l from-[#080808] to-transparent pointer-events-none z-10" />
        </div>
      </div>
    </section>
  );
}
